# Generated by Django 4.0.3 on 2022-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='grateful_for',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='looking_forward_to',
            field=models.TextField(max_length=2000),
        ),
    ]
