# Generated by Django 4.0.3 on 2022-03-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_journalentry_grateful_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='grateful_for',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='looking_forward_to',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
